### ISSUE TITLE
vagrant ssh

### ISSUE THREAD

**Issue by schugh01** [ailispaw/rancheros-iso-box#3]
vagrant ssh
Permission denied (publickey,keyboard-interactive).

If i remove the bellow line from start.sh then it works

if ! grep -q "^PasswordAuthentication no" /etc/ssh/sshd_config; then
  echo "PasswordAuthentication no" >> /etc/ssh/sshd_config
fi

However i have to type the password rancher on vagrant ssh

**Comment by ailispaw** [comment]
Which version of Vagrant do you use?
How was it on vagrant up?

**Comment by schugh01** [comment]
I am using Vagrant 1.7.2
ya this problem occurs when i do vagrant up.

**Comment by ailispaw** [comment]
@schugh01 Thank you.
Is it the same after vagrant destroy and vagrant up again?

**Comment by ailispaw** [comment]
And may I see your Vagrantfile for it?

**Comment by schugh01** [comment]
I have edited your box and using it.

https://github.com/schugh01/chip-rancheros

you can check the Vagrantfile

**Comment by schugh01** [comment]
I have this issue after vagrant destroy and up also :(

**Comment by ailispaw** [comment]
Oh it is not my box...
I will check your script for you.

**Comment by ailispaw** [comment]
You override the home dir as below. So It has changed .ssh, too.
That's why you can not login with public key after vagrant up.

```
config.vm.synced_folder "~", "/home/rancher/", type: "nfs", mount_options: ["nolock", "vers=3", "udp"]
```

You must mount ~ to a different location like /host_home.

Thanks.

**Comment by schugh01** [comment]
Thankyou for your valuable support. I am really impressed by your project. 

One last thing i want to ask you how can i install packages inside rancheros. For example i want git to be installed on rancherbox how can i do that?

**Comment by ailispaw** [comment]
The console container in RancherOS is based on busybox under buildroot by default.
- The easiest way is to use an alternative ubuntu console.

```
[rancher@rancher ~]$ sudo rancherctl service enable ubuntu-console
[rancher@rancher conf]$ exit
$ vagrant reload
$ # It will take a few minutes to download ubuntu image.
$ vagrant ssh
Welcome to RancherOS v0.3.0 (GNU/Linux 3.19.2-rancher x86_64)

 * Documentation:  https://help.ubuntu.com/
rancher@rancher:~$ 
```

Now you can use `apt-get` to install anything you want.

And also you can add it directly in rancher.yml on build as below.

```
services_include:
  ubuntu-console: true
```

Note: My patch, vagrant_plugin_guest_rancheros.rb may not work correctly, because it depends on busybox a bit. You can not use NFS synced folder with ubuntu-console.
- Or in RancherOS manner, you have to use an other application as a container.
- Or RancherOS uses their own busybox build as a base os.
  https://github.com/rancherio/os-base
  You can configure it as you want and build a box with the custom base os.
  Cf.) https://github.com/ailispaw/os-base
  https://github.com/ailispaw/rancheros-lite

Do you really need RancherOS for your project?

**Comment by ailispaw** [comment]
Related to 1.

After vagrant up/reload and ssh, I did the following manually.

```
rancher@rancher:~$ sudo apt-get update
rancher@rancher:~$ sudo apt-get -y install nfs-common portmap
rancher@rancher:~$ sudo mount -o 'nolock,vers=3,udp' 192.168.33.1:'/Users/ailis/Desktop/rancheros' /opt/vagrant
```

Note) It is not persistent. And you had better mount it under /opt, because RancherOS shares /home and /opt with the userdocker container by default.

**Comment by ailispaw** [comment]
Revised.

```
$ vagrant up
$ vagrant ssh
[rancher@rancher ~]$ sudo rancherctl service enable ubuntu-console
[rancher@rancher conf]$ exit
$ vagrant reload
$ # It will take a few minutes to download ubuntu image.
$ # At the first time, NFS mount will fail.
$ vagrant ssh
Welcome to RancherOS v0.3.0 (GNU/Linux 3.19.2-rancher x86_64)

 * Documentation:  https://help.ubuntu.com/
rancher@rancher:~$ sudo apt-get update
rancher@rancher:~$ sudo apt-get -y install nfs-common portmap
rancher@rancher:~$ sudo system-docker ps
CONTAINER ID        IMAGE                          COMMAND                CREATED              STATUS                          PORTS               NAMES
0e8081d294b8        rancher/ubuntuconsole:v0.3.0   "/usr/sbin/entry.sh    About a minute ago   Up About a minute
.
.
.
rancher@rancher:~$ sudo system-docker commit 0e8081d294b8 rancher/ubuntuconsole:v0.3.0
rancher@rancher:~$ exit
$ vagrant reload
```

It should work.

**Comment by ailispaw** [comment]
Oh I misunderstood. You mean a package has to be preinstalled in the box.
VMware Photon might be good for you.
I will create another repo for it.

**Comment by ailispaw** [comment]
Umm. Photon has no NFS support...

**Comment by ailispaw** [comment]
FYI:
https://github.com/ailispaw/photon-box
https://github.com/ailispaw/photon-box/blob/master/scripts/install_packages.sh

I think Photon is more flexible than RancherOS for your purpose currently.

**Comment by ailispaw** [comment]
It seems you have your solution.
https://github.com/schugh01/console-rancheros
